sudo: false
language: python
install:
  - pip install -r requirements.txt
  - pip install tox
script: make tox
env:
  - TOXENV=py27
  - TOXENV=py35
after_success:
  coveralls
notifications:
  slack:
    rooms:
      - sys:yeTvjm0bw1tX6MBWrfkVL5RG#travis
